// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    create: function(req, res) {
      var holderId, pptId, topic;
      pptId = req.param('pptId');
      holderId = req.param('holderId');
      topic = req.param('topic');
      return Meeting.create({
        holder: holderId,
        ppt: pptId,
        topic: topic
      }).exec(function(err, newMeeting) {
        if (err) {
          return res.ok(err);
        }
        return res.json({
          status: 0
        });
      });
    },
    "delete": function(req, res) {
      var meetingId;
      meetingId = req.param('meetingId');
      return Meeting.destroy({
        id: meetingId
      }).exec(function(err) {
        if (err) {
          sails.log(err);
          return res.serverError(err);
        }
        return res.json({
          status: 0
        });
      });
    }
  };

}).call(this);

//# sourceMappingURL=MeetingController.map
