// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    upload: function(req, res) {
      var fileName, pptFile, size, type, userId;
      userId = req.param('userId');
      size = req.param('size');
      type = req.param('type');
      fileName = req.param('fileName');
      pptFile = req.file('file');
      return pptFile.upload(function(err, files) {
        if (err) {
          return res.serverError(err);
        }
        Ppt.create({
          owner: userId,
          fileName: fileName,
          pageCount: 0,
          size: size,
          type: type
        }).exec(function(err, newppt) {
          sails.log(newppt);
          return User.findOne({
            id: userId
          }).populate('ppts').exec(function(err, user) {
            return sails.log(user);
          });
        });
        return res.json({
          message: files.length + ' file(s) uploaded successfully!',
          files: files
        });
      });
    }
  };

}).call(this);

//# sourceMappingURL=PptController.map
