// Generated by CoffeeScript 1.7.1

/*
UserController

@description :: Server-side logic for managing users
@help        :: See http://links.sailsjs.org/docs/controllers
 */

(function() {
  module.exports = {
    login: function(req, res) {
      var email, password;
      email = req.param('email');
      password = req.param('password');
      return User.findOne({
        email: email,
        password: password
      }).exec(function(err, user) {
        if (err) {
          return res.serverError(err);
        }
        if (!user) {
          return res.json({
            status: 101,
            data: 'user not found'
          });
        } else {
          return res.json({
            status: 0,
            data: {
              user: user,
              token: '1234567890'
            }
          });
        }
      });
    },
    signup: function(req, res) {
      var email, name, password;
      email = req.param("email");
      password = req.param("password");
      name = req.param("name");
      return User.findOne({
        email: email
      }).exec(function(err, user) {
        if (user) {
          return res.json({
            status: 101
          });
        }
        return User.create({
          email: email,
          password: password,
          name: name
        }, function(err, newuser) {
          return res.json({
            status: 0,
            user: newuser
          });
        });
      });
    }
  };

}).call(this);

//# sourceMappingURL=UserController.map
